import { useEffect, useState } from "react";
import { aiApi } from "../../api/ai";
import type { AIStatus } from "../../api/ai";
import { Icon } from "../../icons/IconRegistry";
import { Spinner } from "../common/Spinner";
import styles from "./AIStatusWidget.module.css";
import { WidgetCard } from "./WidgetCard";

export function AIStatusWidget({
  editMode,
  ...cardProps
}: {
  editMode: boolean;
  canMoveUp: boolean;
  canMoveDown: boolean;
  onMoveUp: () => void;
  onMoveDown: () => void;
  onHide: () => void;
}) {
  const [status, setStatus] = useState<AIStatus | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    aiApi
      .status()
      .then(setStatus)
      .finally(() => setLoading(false));
  }, []);

  return (
    <WidgetCard title="AI status" icon={<Icon name="sparkles" size={16} />} editMode={editMode} {...cardProps}>
      {loading ? (
        <Spinner label="Checking..." />
      ) : status?.enabled ? (
        <div className={styles.wrap}>
          <span className={`${styles.dot} ${styles.live}`} />
          <div>
            <p className={styles.headline}>Live AI enabled</p>
            <p className={styles.detail}>
              Smart tagging, prioritization, and quick replies are generated by{" "}
              <strong>{status.model}</strong> via {status.provider}.
            </p>
          </div>
        </div>
      ) : (
        <div className={styles.wrap}>
          <span className={`${styles.dot} ${styles.heuristic}`} />
          <div>
            <p className={styles.headline}>Running on heuristics</p>
            <p className={styles.detail}>
              AI features use built-in rule-based logic. Set <code>AI_PROVIDER=anthropic</code> and{" "}
              <code>AI_API_KEY</code> in <code>backend/.env</code> to enable live model output.
            </p>
          </div>
        </div>
      )}
    </WidgetCard>
  );
}
